In [7]:
# Tebellen für die TVD-Analyse erstellen
import pandas as pd
dt = pd.read_csv("Tabellen/tvd_all_methods.csv")
dt["p"] = dt["p"].astype(float)
for dataset_name, df in dt.sort_values(["dataset", "p"]).groupby("p", sort=False):
    print(f"\np = {dataset_name}")
    display(df.reset_index(drop=True))

p = 1.0

,dataset,p,lev - lewis,lev - l2lp,lev - random,l2lp - lewis,lewis - random,l2lp - random
0,Covertype,1.0,0.3194,0.0011,0.1035,0.3183,0.3652,0.1042
1,Example2D,1.0,0.0420,0.0123,0.1061,0.0342,0.0899,0.1033
2,Iris,1.0,0.0355,0.0105,0.0963,0.0312,0.0987,0.0996
3,KDDCup,1.0,0.4336,0.0031,0.2399,0.4306,0.5475,0.2399
4,Webspam,1.0,0.2692,0.0015,0.1117,0.2679,0.2664,0.1116

p = 1.3

,dataset,p,lev - lewis,lev - l2lp,lev - random,l2lp - lewis,lewis - random,l2lp - random
0,Covertype,1.3,0.2695,0.0061,0.1534,0.2634,0.3732,0.1574
1,Example2D,1.3,0.0354,0.0171,0.1335,0.0249,0.1173,0.1291
2,Iris,1.3,0.0289,0.0143,0.1164,0.0233,0.1205,0.1218
3,KDDCup,1.3,0.3690,0.0145,0.2738,0.3549,0.5003,0.2732
4,Webspam,1.3,0.2625,0.0080,0.1469,0.2552,0.2713,0.1468

p = 1.5

,dataset,p,lev - lewis,lev - l2lp,lev - random,l2lp - lewis,lewis - random,l2lp - random
0,Covertype,1.5,0.2159,0.0151,0.2040,0.2009,0.3790,0.2149
1,Example2D,1.5,0.0281,0.0184,0.1501,0.0174,0.1361,0.1450
2,Iris,1.5,0.0223,0.0152,0.1297,0.0171,0.1334,0.1357
3,KDDCup,1.5,0.2964,0.0317,0.2910,0.2655,0.4479,0.2897
4,Webspam,1.5,0.2394,0.0206,0.1754,0.2200,0.2734,0.1764

p = 1.7

,dataset,p,lev - lewis,lev - l2lp,lev - random,l2lp - lewis,lewis - random,l2lp - random
0,Covertype,1.7,0.1451,0.0268,0.2725,0.1183,0.3849,0.2925
1,Example2D,1.7,0.0185,0.0158,0.1648,0.0104,0.1548,0.1601
2,Iris,1.7,0.0144,0.0129,0.1426,0.0106,0.1452,0.1478
3,KDDCup,1.7,0.1948,0.0474,0.3003,0.1484,0.3736,0.2999
4,Webspam,1.7,0.1854,0.0394,0.2132,0.1475,0.2745,0.2183

p = 2.0

,dataset,p,lev - lewis,lev - l2lp,lev - random,l2lp - lewis,lewis - random,l2lp - random
0,Covertype,2.0,0.0346,0.017,0.4078,0.0176,0.3942,0.4011
1,Example2D,2.0,0.0000,0.000,0.1825,0.0000,0.1825,0.1825
2,Iris,2.0,0.0000,0.000,0.1614,0.0000,0.1614,0.1614
3,KDDCup,2.0,0.0000,0.000,0.2945,0.0000,0.2945,0.2945
4,Webspam,2.0,0.0000,0.000,0.3017,0.0000,0.3017,0.3017